### ISSUE TITLE
Compile error with g++ 6.3.0

### ISSUE THREAD

**Issue by dvalenzu** [BenLangmead/bowtie2#122]
Hi,

Compiling with g++ 6.3.0 I got the following errors:

(...)
In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:27:
blockwise_sa.h: In instantiation of ‘class KarkkainenBlockwiseSA<S2bDnaString>’:
blockwise_sa.h:520:48:   required from here
blockwise_sa.h:218:5: error: looser throw specifier for ‘KarkkainenBlockwiseSA<TStr>::~KarkkainenBlockwiseSA() noexcept (false) [with TStr = S2bDnaString]’
     ~KarkkainenBlockwiseSA()
     ^
In file included from bt2_idx.h:42:0,
                 from bt2_build.cpp:27:
blockwise_sa.h:178:7: error:   overriding ‘virtual InorderBlockwiseSA<S2bDnaString>::~InorderBlockwiseSA() noexcept’
 class InorderBlockwiseSA : public BlockwiseSA<TStr> {
       ^~~~~~~~~~~~~~~~~~
(...)

**Comment by ch4rr0** [comment]
The default destructor generated by the compiler for the `InorderBlockwiseSA` class is marked as `noexcept`, however the destructor for `KarkkainenBlockwiseSA` is not marked `noexcept` meaning it's allowed to throw an exception. Since the exceptions specifiers don't match between the two classes the compilation fails.

Since Bowtie 2 is not yet c++11 compliant, the fix is to append `throw()` to `blockwise_sa.h:218`. The empty parens indicate that the function does not throw any exceptions.

I will most likely include this fix in the next Bowtie 2 release.

You can find more information on this issue from the following links:
* http://www.agapow.net/programming/cplusplus/looser-throw-specifier-error-in-c/
* https://msdn.microsoft.com/en-us/library/wfa0edys.aspx

**Comment by BenLangmead** [comment]
@ch4rr0 Do you think we should make such a commit to `master` so others can cherry-pick it?

**Comment by ch4rr0** [comment]
Sure, I don't see any harm in doing so.

**Comment by pelario** [comment]
Thanks !

**Comment by dvalenzu** [comment]
Thanks!
