### ISSUE TITLE
Mac OS 10.12.6

### ISSUE THREAD

**Issue by JohnUrban** [BenLangmead/bowtie2#147]
This might be helpful to some one.

I'm a long-time bowtie2 user - just got a new Mac and couldn't install bowtie2. 
Tried:
- git clone
- source forge zipped source

"make" failed on both.

The solution was (assuming you have home brew):
```
brew install tbb
```

I also followed the home brew note about python - though I don't think this contributed to the solution necessarily:
```
mkdir -p /Users/jurban/Library/Python/2.7/lib/python/site-packages
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/jurban/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

It is fine to close this issue - though I'd recommend updating the documentation if need be to reflect this issue if others have it too.

**Comment by BenLangmead** [comment]
Yes, I agree that we should update the http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#building-from-source section of the manual to include some simple instructions on how to check if TBB is installed, and how to install it.  @ch4rr0 We should also remove the note about "-legacy" packages since we stopped doing that.

**Comment by ch4rr0** [comment]
We updated our documentation to include just that.

http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#building-from-source
