### ISSUE TITLE
Influence of read ID on mapping results

### ISSUE THREAD

**Issue by ilemme** [BenLangmead/bowtie2#151]
Hi,
I was encountering an inconsistency while mapping two almost identical fastq files against the same reference (hg19 human). 
Lines 2-4 of every read in both files are identical, but only the ID in the first line slightly differs.
The mapping statistics for both files were different in the end.

As example of the inconsistency and the dependence on the ID name, I have taken the exact same read twice and changed just the ID and put them into a single file below:

> @2:**3321**:0:31:220293:2087.4:1276.7
>ATTGGCCGGGGGGTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>+
>2&511:,7"(/'&*-.0:<CCCCCCFFC??::886873338:4:3:3959610500006100-4++)4/..,1255
>@2:**test**:0:31:220293:2087.4:1276.7
>ATTGGCCGGGGGGTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>+
>2&511:,7"(/'&*-.0:<CCCCCCFFC??::886873338:4:3:3959610500006100-4++)4/..,1255

The second read is always aligned, while the first one does not align. The order of the reads does not matter. I have checked this with different parameterizations, but could not detect any changes in behavior.

I have used the newest version 2.3.3.1 for this.

Is there any explanation for this behavior I haven't thought about?

Best regards,
Inga

**Comment by BenLangmead** [comment]
This is expected, as the pseudo-random generator is re-initialized for each read, using the read name, sequence and quality values as inputs: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#randomness-in-bowtie-2

**Comment by BenLangmead** [comment]
If it's not desirable for the pseudo-randomness to depend in any way on the read, then you might try the `--non-deterministic` option.  Otherwise, if you want identical results for reads with identical sequence and quality strings (but different names), then you have to change the names to be identical first.  I'll close this for now, since this behavior is documented, but reopen if you think this behavior is posing serious issues.
