### ISSUE TITLE
Unable to use multicore

### ISSUE THREAD

**Issue by codemeleon** [BenLangmead/bowtie2#160]
Hi,

We are using Ubuntu 16.04 on our 32 core server. I am running following bowtie2 command

```bash
bowtie2  -p 30  -q --very-sensitive-local --no-unal -a -x index -1 seq_1.fq.gz -2 seq_2.fq.gz -S res.sam
```

It should be using 30 processor. However, It is using only one.  I tried different versions of bowtie2. However, results were the same. 

I tried other tools like Kraken. they were able to utilize multiple processors.

Please help to resolve processor usage issue with bowtie2

Thanks.

**Comment by BenLangmead** [comment]
That is likely because of `-a`.  With `-a`, the vast majority of the effort being expended by the aligner is simply writing out the very large number of alignments for the most repetitive reads.  That has to be done serially, hence just 1 core.

You could try removing `-a` (or using `-k 10` or some other low-ish number like that) and see if you do much better on utilization.

**Comment by codemeleon** [comment]
Hi @BenLangmead 
Thank for reply.
I removed -a option. However, it didn't change process use.

**Comment by codemeleon** [comment]
Hi @BenLangmead 
Just to let you know. I resolve the problem by recreating the reference index using bowtie2-build.
