### ISSUE TITLE
Malformed sam file after alignment

### ISSUE THREAD

**Issue by xapple** [BenLangmead/bowtie2#165]
I'm getting more strange errors with bowtie, this time after a sucessful run of the program, when I try to convert the resulting sam file to bam file, I do the following:

    cd ~/metagenomics_project/
    bowtie2 -p 16 -x assembly/metaspades/filtered.fasta -1 sample_1/clean/forward_reads.fastq -2 sample_1/clean/reverse_reads.fastq -S bowtie_results/map.sam
    samtools view -bt assembly/metaspades/filtered.fasta.fai bowtie_results/map.sam -o bowtie_results/map.bam -@ 16

I get the following on the standard error from the second program:

    [E::sam_parse1] SEQ and QUAL are of different length
    [W::sam_read1] Parse error at line 23521
    [main_samview] truncated file.

**Comment by ntakebay** [comment]
I got the same problem, and I think it is the same problem as issue #155 and #158: https://github.com/BenLangmead/bowtie2/issues/158
If you look at #158, there is a link to an alpha build, which is supposed to fix the problem.  Alternatively, if you remove -p 16 (i.e. use a single thread instead of 16 threads), it seems to work.

**Comment by ch4rr0** [comment]
Based on feedback we received from others we think this already fixed in v2.3.4.1. Please feel free to reopen if you still see it.
