### ISSUE TITLE
support unaligned bam for input reads (preserving sam tags)

### ISSUE THREAD

**Issue by bwlang** [BenLangmead/bowtie2#195]
Many sequencing centers are producing unaligned BAM files containing RX tags with UMI information.
To preserve UMI information about across alignment, tools like MergeBamAlignments  are used around aligners.   This could be avoided if bowtie2 could consume reads from unaligned BAM files and decorate output records with any tags found in the input bam.

Could such support be reasonably implemented in bowtie2?

**Comment by ch4rr0** [comment]
We're looking into having an implementation available for this. Would it be possible to share a sample BAM file that I can use for testing purposes?

**Comment by bwlang** [comment]
@ch4rr0. yes - I'd be happy to share a small BAM 
I'll try to downsample and attach one here.

**Comment by ch4rr0** [comment]
Any updates on this?

**Comment by bwlang** [comment]
Please find the attached unmapped bam file. It does not have RX tags, but does have RG:Z and XT tags
RG:Z:BC21-INS056:GTTTCG:	
XT:i:21

[combined.ds.bam.zip](https://github.com/BenLangmead/bowtie2/files/2206177/combined.ds.bam.zip)

could be aligned to:
```
>S09-17_001
TTGGTATCAACGGAAGA
>S14-17_013
ACCTGCGGGTGGAGAAA
>S23-17_054
CCTGTTGTGTACGGGCT
>S51-20_089
AGATCTGAGAGGGCTGGGCT
>S56-20_011
TCCTAATCCTCGAGTGTTGT
>S58-20_028
TTTCTCTGGGACCGGCGTAT
>S63-20_045
CTCTAGGCACATCCGCATAT
>S74-22_064
GGTGTCGACAAGCCATTACGTT
>S83-22_059
ATTGGACTTGTTGGACAAGGGT
>S87-22_079
TATGGTAACAGCCGGGCTGCCT
>S89-22_084
CAGCAATATCCAGTTCCTGGAT
>S93-22_092
CATCGAAGTGCTATTTCCGCGG
```

**Comment by ch4rr0** [comment]
We have been actively working on this feature request and have gotten it to work for unpaired reads. Would you be willing to try changes that we have so far?

**Comment by bwlang** [comment]
If it's helpful to you I can test... 
It sounds like you're working on PE mode, which will make the feature much more broadly applicable. In case it's helpful, I think one could make the simplifying assumption for ubam that read pairs are next to each other(I'm not 100% certain about that).

**Comment by ch4rr0** [comment]
>  In case it's helpful, I think one could make the simplifying assumption for ubam that read pairs are next to each other

That's the assumption that we're going with. I just finished adding functionality for paired-end. I will have a binary uploaded soon.

**Comment by ch4rr0** [comment]
Sorry for the delay. Here is the [link](
https://github.com/BenLangmead/bowtie2/releases/download/v2.3.4.2-alpha.2/bowtie2-2.3.4.2-linux-x86_64.zip) to the binary. I have not yet added documentation for changes so here are a few usage examples:

____Align unpaired BAM reads w/o preserving tags____
`bowtie2 -x <path/to/index> -b <path/to/bam>`

____Align unpaired BAM reads w/ tags preserved____
`bowtie2 -x <path/to/index> -b <path/to/bam> --preserve-sam-tags`

____Align paired BAM reads w/o preserving tags____
`bowtie2 -x <path/to/index> -b <path/to/bam> --align-paired-reads`

____Align paired BAM reads w/ tags preserved____
`bowtie2 -x <path/to/index> -b <path/to/bam> --align-paired-reads --preserve-sam-tags`

**Comment by ch4rr0** [comment]
Hello,

Have you gotten a chance to try the changes yet?

**Comment by ch4rr0** [comment]
We have included the changes in our most recent release, v2.3.4.2. Changes are experimental and as such, we solicit feedback on bugs/improvements.

**Comment by siyuanzou9** [comment]
There're a few thing I find little confusing about this function:
1. Assuming read pairs are next to each other. In case of corrupted bam file (missing one line somewhere in the middle), this would mess up with the pairment of every line following. A more robust way would be to decide based on QNAME (as far as I know illumina gives you same name for paired reads) and FLAG (64 for R1, 128 for R2). 
2. Currently (v2.5.4) if the FLAG was set to 64 or 128, I got "0 reads, 0.00% overall alignment rate".
3. If FLAG didn't indicate "unmapped" (4), I got "0 reads, 0.00% overall alignment rate".

I truly appreciate this function. It's very handy for keeping tags that otherwise couldn't pass through the alignment process or require additional workaround (e.g. UMI for RNA-seq, I heard people keep the UMI sequence in the read name during alignment). I hope there would be more instructions on the criteria for a read to be accepted (In case people like me customize codes to convert fastq to bam while including the tag of interest), and more detailed error message when a read is being rejected from alignment, or a pairing error is encountered.

**Comment by siyuanzou9** [comment]
There're a few thing I find little confusing about this function (current version 2.5.4):
1. If FLAG didn't indicate "unmapped" (4), I got "0 reads, 0.00% overall alignment rate".
2. If --align-paired-reads is specified, reads that don't have FLAG indicating it's R1 (64) or R2 (128) doen't get procesed; in case of a bam file with scrambled order (e.g. R1, R1, R1, R1, R2, R2), only R1 read followed by an R2 get recognized as a pair and get processed (In this case the last R1 and the following R2).
3. And this doesn't check anything else for valid pair, including read name. As far as I know illumina gives you same name for paired reads. Having the option to check read name would prevent surprise when something is wrong with the bam.
4. if -align-paired-reads is NOT specified, only reads without R1/R2 FLAG gets procesed.

It took me while to figure out all those hidden rules. Don't get me wrong, I truly appreciate this function. It's very handy for keeping information that otherwise couldn't pass through the alignment process or require additional workaround (e.g. UMI for RNA-seq, I heard people keep the UMI sequence in the read name during alignment). I hope there would be more instructions on the criteria for a read to be accepted (In case people like me customize codes to convert fastq to bam while including the tag of interest), and more detailed error message when some (if not all) reads are rejected from alignment, or a pairing error is encountered.

**Comment by ch4rr0** [comment]
Hello thank you for the feedback,

FYI -- all the options related to BAM input are documented in the Bowtie2 [MANUAL](https://github.com/BenLangmead/bowtie2/MANUAL.markdown).


1. While this would be a nice-to-have we do state in the MANUAL that we only process unaligned BAM reads. Addressing this would either require that we align both aligned and unaligned reads by default, which may be met with angst by some of the userbase, or adding a new flag to opt-in to such behavior. We are currently hesistant on adding new flags to Bowtie2 unless it is something that is overwhelming requested by users.

2. I think, would needlessly complicate the parser in its current state. Here's an example of such unintended consequences: Bowtie2 has a  `--reads-per-batch` option that determines many reads bowtie2 will parse and send to the alignment code for processing. The default is currently 16 reads. What if a user has a BAM file with 32 R1s followed by 32 R2s, this would certainly violate the defaults and lead to unexpected behavior as bowtie2 would not be able to sufficiently fill in the paired-end buffer during parsing. We mention this in the MANUAL that BAM input has to be sorted in order to be processed by Bowtie2. 

>     -b <bam>
Reads are unaligned BAM records sorted by read name. The
--align-paired-reads and --preserve-tags options affect the way Bowtie 2
processes records.

The only way around this is if the user were to split the BAM file into two, one for R1s and the other for R2s. In such a case we can utilize already established command line options such as `-1/-2` to process such files. Wow often would a user do this, ¯\_(ツ)_/¯

3. This is a valid point and would certainly be inline with the requirement stated above.

4. Like 1., would need a second option to align both paired and unpaired, or the user can run two alignments one with the `--aligned-paired-reads` option and one without.

Let me know your thoughts!

**Comment by siyuanzou9** [comment]
Thanks for the thorough response! Now looking back everything is indeed in the manual. I just didn't realize those are actually requirements instead of recommendations (**_unaligned_** BAM records **_sorted by read name_**), nor whether and how bowtie2 checks them (now I know alignment status and R1/R2 are checked through FLAG, while read name order is assumed but not checked), nor the behaviour in case of expections (error message? ignore?). For point 2, I get the technical difficulty. It's always good to know more about how things work. I agree those wouldn't worth adding/changing the codes, though more details and some warnings in manual would certainly help. 

You mentioned split BAM into two, one for R1s and the other for R2s, and use -1/-2 to process such files. As I tested, this doesn't work with BAM files. If you consider support that, it would make the pair requirement much more explict, and I'd imagine you can probably reuse some of the codes for parsing standard pair-end fastq input. 

I believe using BAM format to store raw reads would get more popular, fastq is just too simple and you can't do random access. One example is Oxford Nanopore. They recommend and use BAM as the default raw read format.

**Comment by siyuanzou9** [comment]
A minor issue, the `@PG` tag in the header is not preserved even if --preserve-tags is specified. I get that `@SQ` must be removed and updated with the reference, but I don't see any reason why other tags including `@PG` can't be kept.

**Comment by ch4rr0** [comment]
Hello,

I have gone ahead and made some changes to the way we process BAM input. As referenced in my previous comment the BAM pattern source now works as expected with the `--interleaved` `-1/2` and `-U` command line options.

`--interleave` will align paired BAM records that conform to the following pattern:

``` text
R1
R1
R2
R2
...
```

If you would like to align paired BAM records that conform to a different pattern e.g. (R1, R1, R1, R1, R2, R2, R2, R2) then you can run bowtie2 like so: `./bowtie2 -x index -b -1 bam_file -2 bam_file`. This will cause bowtie2 to open the same file twice filing the two paired end buffers with all the respective R1s and R2s. Word of caution -- make sure that order of reads is consistent in your BAM file. A random mix of R1s and R2s will result in incorrect pairing.

Finally, the `-U` option will cause bowtie2 to align unpaired BAM reads.

The options can be mixed and matched for example to align both paired an unpaired reads in `example/reads/combined_reads.bam`, located in the bowtie2 repo, one would issue the command:

```
bowtie2 -x example/index/lambda_virus -b -U example/reads/combined_reads.bam --interleaved example/reads/combined_reads.bam

16000 reads; of these:
  10000 (62.50%) were paired; of these:
    834 (8.34%) aligned concordantly 0 times
    9166 (91.66%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    834 pairs aligned concordantly 0 times; of these:
      42 (5.04%) aligned discordantly 1 time
    ----
    792 pairs aligned 0 times concordantly or discordantly; of these:
      1584 mates make up the pairs; of these:
        1005 (63.45%) aligned 0 times
        579 (36.55%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
  6000 (37.50%) were unpaired; of these:
    287 (4.78%) aligned 0 times
    5713 (95.22%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
95.03% overall alignment rate
```

The changes are available on the `bug_fixes` branch. Give it a go on your inputs an let me know if there are any issues.

P.S.
`--preserve-tags` only preserves SAM optional tags not the header fields.
