### ISSUE TITLE
TLEN = 0 in some cases of soft clipped reads 

### ISSUE THREAD

**Issue by mcjmigdal** [BenLangmead/bowtie2#203]
I've observed that for some soft clipped reads the reported TLEN is 0 where I believe it shouldn't be. Maybe I'm missing something, below I'm putting reads for which I've observed this behaviour.

```
NS500480:79:HKNCMBGX3:2:11309:20989:6461        81      1       1532    17      37M1S   =       1532    0       TGTAATGAGTGAATAGGTCATTGGGAGATTTCCAAGGG   EEEEAEEAEAEEEEE6EAEAEEEEEEA/E6EEEAAAA/  AS:i:67 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:14G22      YT:Z:UP
NS500480:79:HKNCMBGX3:2:11309:20989:6461        161     1       1532    17      38M     =       1532    0       TGTAATGAGTGAATAGGTCATTGGGAGATTTCCAAGGT   AAAAAEEEEEEEEEAEAEEEEEAEEEEEEEEEEEEEEE  AS:i:69 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:14G23      YT:Z:UP
```
Cheers MM

**Comment by ch4rr0** [comment]
Are you seeing with the most recent version? Would it be possible to share your input files and command line?

**Comment by mcjmigdal** [comment]
Hi,
I'm still using `version 2.3.4.1`. Currently can't share input files. The command line was as follows: `bowtie2 -x path/to/index -1 R1 -2 R2 -p 12 --very-sensitive-local -I 35 -X 2000 --non-deterministic`

I can try with 2.3.4.2 if u think it might help

**Comment by jsh58** [comment]
@mcjmigdal 
The TLEN is 0 because bowtie2 considered the alignments not properly paired (the 0x2 bit of the FLAG is not set).  It doesn't make sense to set a TLEN if the alignments are not properly paired.

The reason why bowtie2 considered the alignments not properly paired is because of the soft-clipped base of the R1 read (CIGAR `37M1S`).  Here are two ways bowtie2 *might* be persuaded to make a different determination:
* include `--dovetail`
* use `end-to-end` alignment instead of `local`
