### ISSUE TITLE
Problem with mapping in bowtie2 

### ISSUE THREAD

**Issue by 21229306832** [BenLangmead/bowtie2#231]
Hi everyone,
I am beginner in Linux and I am trying to do mapping step to identify circRNA in my RNA_seq libraries.
Here what I have done for it:
_ bowtie2-build  Gmax_275_v2.0.fa Gmax_indexed
_bowtie2 -p16 --very-sensitive --score-min=C,-15,0 --mm -x /media/......../Gmax_indexed -q -U -1 001FNT1s1_pe -2 001FNT1S2_pe 2> bowtie2_map_001.log | samtools view -hbuS - | samtools sort - test_vs_Celegans
But it is not happening with the comment (at the end):

 ""--reference FILE
               Reference sequence FASTA FILE [null]""

It would be great if you could help me out with it.
Any comments would be appropriated.

Best,
Essi

**Comment by ch4rr0** [comment]
Since you are aligning paired-end reads, you should not provide the `-U` option since `-1`/`-2`, and `-U` are mutually exclusive. This will cause `bowtie2` to error out as your `bowtie2_map_001.log` file will indicate.

The error message you see is `samtools view` usage output indicating that the `bowtie2` command failed.

Hope this helps.

**Comment by ch4rr0** [comment]
I am closing this issue.
