### ISSUE TITLE
Possible memory leak in bowtie2-align (2.3.4.2)

### ISSUE THREAD

**Issue by kemball** [BenLangmead/bowtie2#241]
I'm trying to align some long reads (~35GB) to a relatively small genome (~20MB). The machine I'm using has 500+ GB RAM, but nonetheless bowtie2-align slowly consumed more and more RAM until it was killed for using too much.

> Time loading reference: 00:00:00
> Time loading forward index: 00:00:00
> Time loading mirror index: 00:00:00
> Killed
> Use of uninitialized value $l in scalar chomp at /usr/bin/bowtie2 line 589, <BT> line 3237761.
> Use of uninitialized value $l in substitution (s///) at /usr/bin/bowtie2 line 590, <BT> line 3237761.
> Use of uninitialized value $l in print at /usr/bin/bowtie2 line 594, <BT> line 3237761.
> (ERR): bowtie2-align exited with value 137

All my reads are unpaired .fastq with phred score 0 , and I was using `--very-sensitive` and `--local`. Am I doing something pathological to the index data structures? 

I've updated to the most recent version of bowtie2, but even the latest from bioconda (2.3.5?) consumes 120 GB on start and slowly consumes more memory over time, whether or not I use --ignore-quals and on any sensitivity. That seems like it's not supposed to be happening.

**Comment by ch4rr0** [comment]
I have been profiling with both `valgrind` (Linux), and `Instruments` (MacOS), but have not found any leaks yet. Bowtie2's memory footprint is surely affected by read length, index size, and Alignment options. If aligning multi-threaded the number of threads specified  can somewhat serve as a multiplying factor since each thread gets its own DP matrix. With that said can you provide me with additional details on your:
* Average read length
* Number of threads used for alignment

**Comment by kemball** [comment]
I did a bit more poking around and turned up a couple interesting facts. The reads are very long, on average 3700 bases, and they're not RNA reads but DNA reads. 

I suspect that the tremendous memory usage has something to do with the read length, since running twice as many reads of length 100-150 uses less than a thousandth of the memory.

So, uh, PEBKAC, or more accurately "don't try and map pacbio reads, it'll never work".
